 version: '3.7'
 services:
 
   dashboard:
     build: 
       context: ./
     container_name: dash-app_dashboard      
     hostname: dash-app_dashboard
     #restart: always
     #volumes:
     # - C:\Users\piebar\.ssh:/home/user/.ssh:ro
     ports:
       - 5000:80
     networks:
       - network 
    
 networks:
   network:
     driver: bridge